# Generated by Django 5.0.6 on 2025-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpeg", upload_to="profile_pics"),
        ),
    ]
